/* Generated by Rae C backend (experimental) */
#include <stdint.h>
#include <string.h>
#include "rae_runtime.h"

extern const char* rae_ext_rae_io_read_line(void);
extern int64_t rae_ext_rae_io_read_char(void);
RAE_UNUSED static const char* rae_readLine_(void);
RAE_UNUSED static int64_t rae_readChar_(void);
extern int64_t rae_ext_rae_str_len(const char* s);
extern int64_t rae_ext_rae_str_compare(const char* a, const char* b);
extern int8_t rae_ext_rae_str_eq(const char* a, const char* b);
extern int64_t rae_ext_rae_str_hash(const char* s);
extern const char* rae_ext_rae_str_concat(const char* a, const char* b);
extern const char* rae_ext_rae_str_sub(const char* s, int64_t start, int64_t len);
extern int8_t rae_ext_rae_str_contains(const char* s, const char* sub);
extern int8_t rae_ext_rae_str_starts_with(const char* s, const char* prefix);
extern int8_t rae_ext_rae_str_ends_with(const char* s, const char* suffix);
extern int64_t rae_ext_rae_str_index_of(const char* s, const char* sub);
extern const char* rae_ext_rae_str_trim(const char* s);
extern double rae_ext_rae_str_to_f64(const char* s);
extern int64_t rae_ext_rae_str_to_i64(const char* s);
RAE_UNUSED static int64_t rae_length_String_(const char* this);
RAE_UNUSED static int64_t rae_compare_String_String_(const char* this, const char* other);
RAE_UNUSED static int8_t rae_equals_String_String_(const char* this, const char* other);
RAE_UNUSED static int64_t rae_hash_String_(const char* this);
RAE_UNUSED static const char* rae_concat_String_String_(const char* this, const char* other);
RAE_UNUSED static const char* rae_sub_String_Int_Int_(const char* this, int64_t start, int64_t len);
RAE_UNUSED static int8_t rae_contains_String_String_(const char* this, const char* sub);
RAE_UNUSED static int8_t rae_startsWith_String_String_(const char* this, const char* prefix);
RAE_UNUSED static int8_t rae_endsWith_String_String_(const char* this, const char* suffix);
RAE_UNUSED static int64_t rae_indexOf_String_String_(const char* this, const char* sub);
RAE_UNUSED static const char* rae_trim_String_(const char* this);
RAE_UNUSED static double rae_toFloat_String_(const char* this);
RAE_UNUSED static int64_t rae_toInt_String_(const char* this);

RAE_UNUSED static const char* rae_readLine_(void) {
  return rae_ext_rae_io_read_line();
}

RAE_UNUSED static int64_t rae_readChar_(void) {
  return rae_ext_rae_io_read_char();
}

RAE_UNUSED static int64_t rae_length_String_(const char* this) {
  return rae_ext_rae_str_len(this);
}

RAE_UNUSED static int64_t rae_compare_String_String_(const char* this, const char* other) {
  return rae_ext_rae_str_compare(this, other);
}

RAE_UNUSED static int8_t rae_equals_String_String_(const char* this, const char* other) {
  return rae_ext_rae_str_eq(this, other);
}

RAE_UNUSED static int64_t rae_hash_String_(const char* this) {
  return rae_ext_rae_str_hash(this);
}

RAE_UNUSED static const char* rae_concat_String_String_(const char* this, const char* other) {
  return rae_ext_rae_str_concat(this, other);
}

RAE_UNUSED static const char* rae_sub_String_Int_Int_(const char* this, int64_t start, int64_t len) {
  return rae_ext_rae_str_sub(this, start, len);
}

RAE_UNUSED static int8_t rae_contains_String_String_(const char* this, const char* sub) {
  return rae_ext_rae_str_contains(this, sub);
}

RAE_UNUSED static int8_t rae_startsWith_String_String_(const char* this, const char* prefix) {
  return rae_ext_rae_str_starts_with(this, prefix);
}

RAE_UNUSED static int8_t rae_endsWith_String_String_(const char* this, const char* suffix) {
  return rae_ext_rae_str_ends_with(this, suffix);
}

RAE_UNUSED static int64_t rae_indexOf_String_String_(const char* this, const char* sub) {
  return rae_ext_rae_str_index_of(this, sub);
}

RAE_UNUSED static const char* rae_trim_String_(const char* this) {
  return rae_ext_rae_str_trim(this);
}

RAE_UNUSED static double rae_toFloat_String_(const char* this) {
  return rae_ext_rae_str_to_f64(this);
}

RAE_UNUSED static int64_t rae_toInt_String_(const char* this) {
  return rae_ext_rae_str_to_i64(this);
}

int main(void) {
  const char* s = "  hello world  ";
  const char* t = rae_trim_String_(s);
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Trimmed: '", rae_ext_rae_str(t)), "'"));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Starts with 'hello': ", rae_ext_rae_str(rae_startsWith_String_String_(t, "hello"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Starts with 'world': ", rae_ext_rae_str(rae_startsWith_String_String_(t, "world"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Ends with 'world': ", rae_ext_rae_str(rae_endsWith_String_String_(t, "world"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Ends with 'hello': ", rae_ext_rae_str(rae_endsWith_String_String_(t, "hello"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Index of 'world': ", rae_ext_rae_str(rae_indexOf_String_String_(t, "world"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Index of 'none': ", rae_ext_rae_str(rae_indexOf_String_String_(t, "none"))), ""));
  rae_ext_rae_log_cstr(rae_ext_rae_str_concat(rae_ext_rae_str_concat("Contains 'lo wo': ", rae_ext_rae_str(rae_contains_String_String_(t, "lo wo"))), ""));
  return 0;
}

