/* Generated by Rae C backend (experimental) */
#include <stdint.h>
#include <string.h>
#include "rae_runtime.h"

extern int64_t nextTick(void);
extern void sleepMs(int64_t ms);
extern RaeList* rae_list_create(int64_t cap);
extern void rae_list_add(RaeList* list, int64_t value);
extern int64_t rae_list_get(RaeList* list, int64_t index);
extern int64_t rae_list_length(RaeList* list);
extern void rae_seed(int64_t n);
extern double rae_random(void);
extern int64_t rae_random_int(int64_t min, int64_t max);
RAE_UNUSED static void seed(int64_t n);
RAE_UNUSED static double random(void);
RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max);
RAE_UNUSED static int64_t add(int64_t a, int64_t b);
RAE_UNUSED static int64_t triple(int64_t value);
RAE_UNUSED static int64_t chain(int64_t a, int64_t b, int64_t c);

RAE_UNUSED static void seed(int64_t n) {
  rae_seed(n);
}

RAE_UNUSED static double random(void) {
  return rae_random();
}

RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max) {
  return rae_random_int(min, max);
}

RAE_UNUSED static int64_t add(int64_t a, int64_t b) {
  return (a + b);
}

RAE_UNUSED static int64_t triple(int64_t value) {
  return (value * 3);
}

RAE_UNUSED static int64_t chain(int64_t a, int64_t b, int64_t c) {
  return (triple((a + b)) + c);
}

int main(void) {
  rae_log_cstr("VM math demo start");
  rae_log_i64(add(2, 5));
  rae_log_i64(triple(4));
  rae_log_i64(chain(1, 2, 3));
  rae_log_cstr("VM math demo end");
  return 0;
}

