/* Generated by Rae C backend (experimental) */
#include <stdint.h>
#include <string.h>
#include "rae_runtime.h"

typedef struct {
  RaeAny* data;
  int64_t length;
  int64_t capacity;
} List2;

extern int64_t nextTick(void);
extern int64_t rae_time_ms(void);
extern void sleepMs(int64_t ms);
extern RaeList* rae_list_create(int64_t cap);
extern void rae_list_add(RaeList* list, int64_t value);
extern int64_t rae_list_get(RaeList* list, int64_t index);
extern int64_t rae_list_length(RaeList* list);
extern void rae_seed(int64_t n);
extern double rae_random(void);
extern int64_t rae_random_int(int64_t min, int64_t max);
RAE_UNUSED static void seed(int64_t n);
RAE_UNUSED static double random(void);
RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max);
RAE_UNUSED static List2 createList2(int64_t initialCap);
RAE_UNUSED static void grow(List2* this);
RAE_UNUSED static void add(List2* this, RaeAny value);
RAE_UNUSED static RaeAny get(List2* this, int64_t index);
RAE_UNUSED static void set(List2* this, int64_t index, RaeAny value);
RAE_UNUSED static void insert(List2* this, int64_t index, RaeAny value);
RAE_UNUSED static RaeAny pop(List2* this);
RAE_UNUSED static void remove(List2* this, int64_t index);
RAE_UNUSED static void clear(List2* this);
RAE_UNUSED static int64_t length(List2* this);

RAE_UNUSED static void seed(int64_t n) {
  rae_seed(n);
}

RAE_UNUSED static double random(void) {
  return rae_random();
}

RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max) {
  return rae_random_int(min, max);
}

RAE_UNUSED static List2 createList2(int64_t initialCap) {
  return (List2){ .data = rae_buf_alloc(initialCap, sizeof(RaeAny)), .length = 0, .capacity = initialCap };
}

RAE_UNUSED static void grow(List2* this) {
  int64_t newCap = this->capacity * 2;
  if (newCap == 0) {
  newCap = 4;
  }
  RaeAny* newData = rae_buf_alloc(newCap, sizeof(RaeAny));
  rae_buf_copy(this->data, 0, newData, 0, this->length, sizeof(RaeAny));
  rae_buf_free(this->data);
  this->data = newData;
  this->capacity = newCap;
}

RAE_UNUSED static void add(List2* this, RaeAny value) {
  if (this->length == this->capacity) {
  grow(this);
  }
  ((RaeAny*)(this->data))[this->length] = rae_any(value);
  this->length = this->length + 1;
}

RAE_UNUSED static RaeAny get(List2* this, int64_t index) {
  if (index < 0 || index >= this->length) {
  return 0;
  }
  return ((RaeAny*)(this->data))[index];
}

RAE_UNUSED static void set(List2* this, int64_t index, RaeAny value) {
  if (index < 0 || index >= this->length) {
  return;
  }
  ((RaeAny*)(this->data))[index] = rae_any(value);
}

RAE_UNUSED static void insert(List2* this, int64_t index, RaeAny value) {
  if (index < 0 || index > this->length) {
  return;
  }
  if (this->length == this->capacity) {
  grow(this);
  }
  if (index < this->length) {
  rae_buf_copy(this->data, index, this->data, index + 1, this->length - index, sizeof(RaeAny));
  }
  ((RaeAny*)(this->data))[index] = rae_any(value);
  this->length = this->length + 1;
}

RAE_UNUSED static RaeAny pop(List2* this) {
  if (this->length == 0) {
  return 0;
  }
  RaeAny val = ((RaeAny*)(this->data))[this->length - 1];
  this->length = this->length - 1;
  return val;
}

RAE_UNUSED static void remove(List2* this, int64_t index) {
  if (index < 0 || index >= this->length) {
  return;
  }
  if (index < this->length - 1) {
  rae_buf_copy(this->data, index + 1, this->data, index, this->length - index - 1, sizeof(RaeAny));
  }
  this->length = this->length - 1;
}

RAE_UNUSED static void clear(List2* this) {
  this->length = 0;
}

RAE_UNUSED static int64_t length(List2* this) {
  return this->length;
}

int main(void) {
  rae_log_cstr("List2 Any Test");
  List2 list = createList2(2);
  add(&(list), rae_any(10));
  add(&(list), rae_any("Hello"));
  add(&(list), rae_any(1));
  add(&(list), rae_any(3.14));
  rae_log_cstr("List items:");
  int64_t i = 0;
  {
  while (i < length(&(list))) {
  rae_log_any(get(&(list), i));
  i = i + 1;
  }
  }
  rae_log_cstr("Done.");
  return 0;
}

