/* Generated by Rae C backend (experimental) */
#include <stdint.h>
#include <string.h>
#include "rae_runtime.h"

typedef struct {
  void* data;
  int64_t length;
  int64_t capacity;
} List2;

extern int64_t nextTick(void);
extern int64_t rae_time_ms(void);
extern void sleepMs(int64_t ms);
extern RaeList* rae_list_create(int64_t cap);
extern void rae_list_add(RaeList* list, int64_t value);
extern int64_t rae_list_get(RaeList* list, int64_t index);
extern int64_t rae_list_length(RaeList* list);
extern void rae_seed(int64_t n);
extern double rae_random(void);
extern int64_t rae_random_int(int64_t min, int64_t max);
RAE_UNUSED static void seed(int64_t n);
RAE_UNUSED static double random(void);
RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max);
RAE_UNUSED static List2 createList2(int64_t initialCap);
RAE_UNUSED static void grow(List2* this);
RAE_UNUSED static void add(List2* this, RaeAny value);
RAE_UNUSED static RaeAny get(List2* this, int64_t index);

RAE_UNUSED static void seed(int64_t n) {
  rae_seed(n);
}

RAE_UNUSED static double random(void) {
  return rae_random();
}

RAE_UNUSED static int64_t randomInt(int64_t min, int64_t max) {
  return rae_random_int(min, max);
}

RAE_UNUSED static List2 createList2(int64_t initialCap) {
  return (List2){ .data = rae_buf_alloc(initialCap, sizeof(RaeAny)), .length = 0, .capacity = initialCap };
}

RAE_UNUSED static void grow(List2* this) {
  int64_t newCap = this->capacity * 2;
  if (newCap == 0) {
  newCap = 4;
  }
  void* newData = rae_buf_alloc(newCap, sizeof(RaeAny));
  rae_buf_copy(this->data, 0, newData, 0, this->length, sizeof(RaeAny));
  rae_buf_free(this->data);
  this->data = newData;
  this->capacity = newCap;
}

RAE_UNUSED static void add(List2* this, RaeAny value) {
  if (this->length == this->capacity) {
  grow(this);
  }
  ((int64_t*)(this->data))[this->length] = value;
  this->length = this->length + 1;
}

RAE_UNUSED static RaeAny get(List2* this, int64_t index) {
  if (index < 0 || index >= this->length) {
  return ((int64_t*)(this->data))[0];
  }
  return ((int64_t*)(this->data))[index];
}

int main(void) {
  rae_log_cstr("Generic List2 Test (Int)");
  List2 list = createList2(2);
  add(&(list), rae_any(10));
  add(&(list), rae_any(20));
  add(&(list), rae_any(30));
  rae_log_cstr("List items:");
  int64_t i = 0;
  {
  while (i < list.length) {
  rae_log_i64(get(&(list), i));
  i = i + 1;
  }
  }
  rae_log_cstr("Generic List2 Test (String)");
  List2 slist = createList2(2);
  add(&(slist), rae_any("Hello"));
  add(&(slist), rae_any("Generics"));
  rae_log_cstr("List items:");
  int64_t j = 0;
  {
  while (j < slist.length) {
  rae_log_i64(get(&(slist), j));
  j = j + 1;
  }
  }
  rae_log_cstr("Done.");
  return 0;
}

