#!/usr/bin/env bash
# Generates build/version_gen.h from compiler/VERSION + the current git state.
# Run by the Makefile before compiling main.c (see #930,
# docs/versioning-and-toolchain.md §1). Never edit the generated header by
# hand — it is overwritten on every build.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

VERSION_BASE="$(tr -d ' \t\n\r' < VERSION)"

# Only semver release tags (v0.1.0, ...) count — the repo has older
# non-release tags (e.g. VERY_GOOD_FOR_DEMO) that --match excludes.
TAG_GLOB='v[0-9]*.[0-9]*.[0-9]*'

GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
GIT_DATE="$(git log -1 --format=%cd --date=format:%Y-%m-%d HEAD 2>/dev/null || echo unknown)"

EXACT_TAG="$(git describe --tags --match "$TAG_GLOB" --exact-match HEAD 2>/dev/null || true)"
LAST_TAG="$(git describe --tags --match "$TAG_GLOB" --abbrev=0 HEAD 2>/dev/null || true)"

if [ -n "$EXACT_TAG" ]; then
  IS_RELEASE=1
else
  IS_RELEASE=0
fi

if [ -n "$LAST_TAG" ]; then
  COMMITS_SINCE_TAG="$(git rev-list --count "${LAST_TAG}..HEAD" 2>/dev/null || echo 0)"
else
  # No semver tag exists yet in this checkout — fall back to total commit
  # count so a pre-first-tag build still prints a meaningful -dev.N.
  COMMITS_SINCE_TAG="$(git rev-list --count HEAD 2>/dev/null || echo 0)"
fi

# Dirty = tracked-file changes only (staged or unstaged), matching
# `git describe --dirty`'s own definition — untracked files don't count.
if git diff --quiet 2>/dev/null && git diff --cached --quiet 2>/dev/null; then
  GIT_DIRTY=0
else
  GIT_DIRTY=1
fi

cat <<EOF
#ifndef RAE_VERSION_GEN_H
#define RAE_VERSION_GEN_H
/* Generated by tools/gen-version-header.sh — do not edit by hand. */
#define RAE_VERSION_BASE "$VERSION_BASE"
#define RAE_GIT_COMMIT "$GIT_COMMIT"
#define RAE_GIT_DATE "$GIT_DATE"
#define RAE_GIT_TAG "$LAST_TAG"
#define RAE_IS_RELEASE $IS_RELEASE
#define RAE_COMMITS_SINCE_TAG $COMMITS_SINCE_TAG
#define RAE_GIT_DIRTY $GIT_DIRTY
#endif
EOF
